### ISSUE TITLE
Homepage background image not cycling or even loading

### ISSUE THREAD

**Issue by JamieSinn** [thetomester13/homepage#1]
To continue the conversation on reddit.
https://dashboard.jamiesinn.ca/
https://dashboard.jamiesinn.ca/hp_assets/lib/ajax_get_image.php

**Comment by tomershvueli** [comment]
I suspect that the 'file_get_contents' function didn't work for an external URL with certain security settings. Try pulling the latest 21580b891c09f9e21ae9c409fdcaae2f0b6c88e0 commit and try again.

**Comment by JamieSinn** [comment]
There we go. 

Thanks!
