### ISSUE TITLE
Unsplash instructions not clear

### ISSUE THREAD

**Issue by kominoshja** [thetomester13/homepage#10]
Hi! I tried to install homepage, but I can't get it to work with unsplash. Can we document how to do that? Or at least add a link?

**Comment by tomershvueli** [comment]
The main README file has a link to the [Unsplash Developers](https://unsplash.com/developers) page. There you can get Unsplash client ID and plug it into your config.json file. Is that not working for you?

**Comment by kominoshja** [comment]
Yeah, I'm not able to recognize where to get the client ID...

**Comment by tomershvueli** [comment]
On the Unsplash Developers page you must 'Register as a Developer'. From there you'll be to create a new application and get your client ID.
