### ISSUE TITLE
Information from config.json viewable in page source.

### ISSUE THREAD

**Issue by beaglie** [thetomester13/homepage#14]
Hi,

Love the project. Nice and simple. I'm setting it up for use right now!

One thing. I noticed the .htaccess file blocking direct access to the config.json file, but if you view the source of the page, all the JSON data is sitting there. Exposing the UnSplash API Key like that does not seem great.

Is there a way you do not need to load this into the HTML (javascript) of the page?

**Comment by tomershvueli** [comment]
Good find! Thanks for bringing this to my attention; I'll get to this soon. Feel free to put in a PR if you want to take a stab at it!

**Comment by tomershvueli** [comment]
@beaglie sorry for the late response! This should be fixed now with the latest commit, 14caa89f6ced240480988f9266e8da40ac461a15.
