### ISSUE TITLE
responsive website

### ISSUE THREAD

**Issue by thomascriscione** [thetomester13/homepage#17]
Hey,

I have had to modify the code to run it on my mobile:

I have changed:

`@media (min-width: 992px) {
  #links-wrap {margin-top: 15%; height: auto; font-size: 80px;}

  #clock-wrap {font-size: 30px;}
}`

to: 

`@media (max-width: 400px) {
  #links-wrap {margin-top: 25%; height: auto; font-size: 45px;}

  #clock-wrap {font-size: 20px;}
}
`

**Comment by tomershvueli** [comment]
Hey @thomascriscione thanks for the breakdown. What wasn't working for you with the previous code? Can you create a PR with your code changes so I can test it out before merging it in?

**Comment by thomascriscione** [comment]
First, I am not an expert at all, so do not hesitate to correct me if I am wrong !

For me the condition for the mobile view: min-width: 992px is valid if the min width resolution is over 992 however the mobile width resolution is 360 so the condition can't work.

With the condition max-width: 400px, it will switch perfectly with all standard mobile resolution.

for the 80 to 45px, it just a matter of customization !

**Comment by tomershvueli** [comment]
I'm not able to replicate a mobile screen that doesn't have the mobile styles applied. Which mobile view are you working with specifically? Do you have any steps to replicate?

**Comment by thomascriscione** [comment]
Hello,
I have tried on both S9 or IphoneX.
I can send you my own url where I have hosted your app for your test.
Kind regards,

**Comment by tomershvueli** [comment]
Thanks for your message @thomascriscione. I just pushed up c79cf8e477b8870e44aa463f83b6af035709da37 that should hopefully help with some mobile/tablet styles.
