### ISSUE TITLE
Make it possible to put items into "directories"

### ISSUE THREAD

**Issue by MetalCar** [thetomester13/homepage#23]
I have a lot of items, that come into my mind, while setting up my config.json. So I would like to have directories. These can be configured by nesting items.

**Comment by tomershvueli** [comment]
How would you see this displayed in the UI? The purpose of homepage is to keep things very simple and I'm afraid this may be complicating things.

**Comment by MetalCar** [comment]
In the UI it should be displayed as it is, a directory. So if you click on that icon with a new you open the directory....like a explorer. So it is possible to add more items by grouping them.

**Comment by tomershvueli** [comment]
This would add a bit of complexity that I'm hoping to avoid. I'd rather not go down this route in the meantime unless more users show interest.

**Comment by tomershvueli** [comment]
Closing as this is out of scope of this project.
