### ISSUE TITLE
Uncaught TypeError: array_merge()

### ISSUE THREAD

**Issue by apreeel** [thetomester13/homepage#25]
Hi, thanks a lot for your work, i'm new to PHP, i've been using your homepage for a while, but suddenly it started to show this error:
`Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in X:\web\src\index.php:19 Stack trace: #0 X:\web\src\index.php(19): array_merge() #1 {main} thrown in X:\web\src\index.php on line 19`

I was trying to google it but no success. Could you help me to figure it out?

**Comment by tomershvueli** [comment]
Weird that this was working for a while but isn't anymore. The error would seem to suggest that the `array_merge` method is now being passed in `null` for the 2nd value - does your `config.json` file still exist in the proper directory? If so, did your PHP version recently get updated? What version are you on now?

**Comment by apreeel** [comment]
Sorry for disturbing - it started to work when i was trying different PHP versions (from 8.0.0 to 5.6 or 5.3) - but wont load any menu/buttons - there were few messed commas in `config.json`, that i already fixed.
Then i changed PHP back to 8.0 and it still working.
I guess the reason is somewhere around IIS manager which i'm accidentally using. 
Anyway, thank you again for your project and such quick response.

**Comment by tomershvueli** [comment]
> Anyway, thank you again for your project and such quick response.

Happy to! Thanks for using my project :)
