### ISSUE TITLE
Can't get Random Custom_URL_Selector To Work

### ISSUE THREAD

**Issue by armouredking** [thetomester13/homepage#26]
Honestly not sure what is wrong here. I've tried iterations of "[{random}]", "['{random}']", [{random}], ['{random}']. Removing the quotes causes some transparent breakage (mostly background sayagata-400px.png has an odd appearance probably caused by the missing quotes throwing errors).

Assuming the use of "[{random}]" from README.md, what I see in my browser console for headers on ```ajax_get_image.php``` looks like this:

```{"success":1,"url":null}```

So the ```ajax_get_image.php``` file call is not able to get the url of images for me when using {random}. Changing from {random} to any of the selectors in the file (ex 'bga') will cause that _one_ image to load (interestingly the message remains success:1 with url no longer null but an actual address), but I would like to use the random feature properly and cycle through several images that are listed in my custom_url json file.

I looked at the function from ```ajax_get_image.php``` on line 24 but I'll be honest, code reading/writing is not my forte. I have a general idea of what should be happening, but no idea how to debug further.

On a couple of tangents, I also noticed that:
1) Custom_URL doesn't seem to be able to accept {{cur}} variable. Nor does it seem to accept a relational url. If I want Custom_URL to work, I have to enter the entire URL, even if my JSON file is located on the same server / path as the rest of the web files.
2) The credits feature also doesn't seem to work when using custom_urls. I get ```Picture by / Unsplash``` in the credit section, and looking at the code I think the user's name is supposed to appear before that / (line 70, column 38-72 of index.php file). The best option if possible is to get it so that the credit section checks for ```protected``` being empty, and if not it uses the json file from our ```protected``` section to dynamically create values. I'm not that familiar with json so not sure how the arrays have to be structured. If possible, could we define a url to the image, the artist's name, and the artist's portfolio link in our custom json file and have it generates the image credits matched to the url? Also not sure if the picture refresh actually reloads the entire page or not (I think that or another ajax would be required to update the credit section, no?) so if not possible to do that just have the ```Picture by / Unsplash``` message hidden when using the ```protected``` section.

**Comment by tomershvueli** [comment]
Thanks for the detailed breakdown and for using homepage, @armouredking !

- I checked and am able to properly use `[{random}]` for custom URL's. For example, if your `custom_url` is set to an Unsplash API page like so: `https://api.unsplash.com/photos?page=1&client_id={client id}`, then your `custom_url_selector` could be set to `[{random}]['urls']['raw']`, which will pull in a random image from the Unsplash API. 
- You're right in that the `custom_url` value itself did not support the `{{cur}}` parameter for relative URL's. That has now been resolved. So you should be able to do something like `{{cur}}/images.json` for the `custom_url` parameter. 
- The Unsplash link back modal was never supposed to have been shown when using a custom URL. This has now been corrected. 

Hope this helps!

**Comment by tomershvueli** [comment]
Closing since I haven't heard an update. Comment again if you're still having issues.
