### ISSUE TITLE
Unsplash  - unsplash_client_id

### ISSUE THREAD

**Issue by kjanezic95** [thetomester13/homepage#27]
Hello, I have been trying to get Unsplash to work, but I get no image background. 

What I did:
- registered Unsplash dev acc
- made a demo app
- used demo app "Access key" as "unsplash_client_id" in config.json

Did I miss something or is this function not functional anymore?

Thank you in advance

**Comment by tomershvueli** [comment]
This is working fine on my end. If you open up the dev console, are you able to see any errors in the console, or glean any insights from the Network tab? If you tap 'r' on your keyboard while the Network tab is open, it should trigger a fresh request to the ajax_get_image.php script.

**Comment by tomershvueli** [comment]
Closing. Comment again if you're still having issues.
