### ISSUE TITLE
Make wallpapers cover/stretch to fit the browser window

### ISSUE THREAD

**Issue by mikkelnl** [thetomester13/homepage#3]
It'll now tile/repeat:

![schermafbeelding 2016-10-11 om 15 38 08](https://cloud.githubusercontent.com/assets/1759050/19272464/ed4817c2-8fc8-11e6-83a3-56bee033db13.png)

**Comment by tomershvueli** [comment]
Try pulling the latest 10bfc5e1d2540454dff1c5c5bac0ed5c4b11c0c8 commit and try it out. Turns out my screen isn't as big as yours so I didn't see the tiling ;)

**Comment by mikkelnl** [comment]
Yep, works fine, thanks :)
