### ISSUE TITLE
Toggling the menu on mobile

### ISSUE THREAD

**Issue by Strap1** [thetomester13/homepage#4]
I might have missed something obvious but how do we toggle the menu on a mobile device where the keyboard is not visible?

**Comment by tomershvueli** [comment]
You didn't miss anything. This is at the top of my to-do list. Hoping to have something out for this in the coming weeks, stay tuned!

**Comment by tomershvueli** [comment]
Try pulling the latest (c2b86ce) and giving it a whirl!

**Comment by Strap1** [comment]
Will do. Nice one!
