### ISSUE TITLE
Feature Request: Allow Overlay Timer Switch

### ISSUE THREAD

**Issue by aljawaid** [thetomester13/homepage#5]
Excellent dashboard but is there a way for the webpage to go back to a blank cover page after xx seconds?

Would be nice if we could have a setting in the config to allow a timeout of xx seconds.  This will help keeping the page visibly hidden.

**Comment by tomershvueli** [comment]
Hmm, how do you mean 'blank cover page'? Are you referring to automatically hiding the menu after a certain timeout?

**Comment by aljawaid** [comment]
Thanks for replying, yes that's exactly what I mean.

**Comment by tomershvueli** [comment]
Got it, great idea! Stay tuned.

**Comment by tomershvueli** [comment]
Pull the latest 9c1a519 and give it a whirl!

**Comment by aljawaid** [comment]
Thank you so much! It works nicely!

**Comment by aljawaid** [comment]
![snip_20170304005706](https://cloud.githubusercontent.com/assets/10233708/23574360/86f8d858-0075-11e7-8c26-75685ec1ed70.png)

This is how I have adapted mine :-)

**Comment by tomershvueli** [comment]
Looks great! Glad to see you made it your own :)
