### ISSUE TITLE
Homepage showing just an empty page

### ISSUE THREAD

**Issue by adrianmihalko** [thetomester13/homepage#7]
Hi,

I cloned this repo and renamed config.sample.json to config.json.

All I get is an empty page:

<img width="1244" alt="screen shot 2017-09-15 at 21 48 09" src="https://user-images.githubusercontent.com/733361/30500650-9d717142-9a5f-11e7-9e44-586e874d67f6.png">

Resources are accessible (except one which you can see), Apache&PHP is installed.

Any suggestion?

**Comment by aljawaid** [comment]
press the space bar

**Comment by adrianmihalko** [comment]
Oh, missed that! Thanks. :)
