### ISSUE TITLE
How can I change the amount of time it takes to change background photo?

### ISSUE THREAD

**Issue by nyex** [thetomester13/homepage#9]
Thanks a lot for the work, by the way! Perfect for our needs :)

I was just wondering where can I change how long it takes before the background image changes. I've been looking around but no luck so far...

**Comment by nyex** [comment]
I figured it out! It's in /hp_assets/js/main.js
It didn't work at first because I had to clean my browser's cache ¬¬
Ops.

**Comment by tomershvueli** [comment]
I think that value actually makes sense as a config variable, so you should see the new `time_to_refresh_bg` variable in the newest commit, 88fcf81989a36a29b3cd5c08df9d38b5382e4b0d!
